version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test_password
      #MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DATABASE: test_primary_key
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 300M
    volumes:
      - ./db_data:/var/lib/mysql

